# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('AUCUNE', 'Aucune'), ('Z1', 'Nord et Extrême Nord'), ('Z2', 'Adamaoua, département du mbam'), ('Z3', 'Ouest et Nord-Ouest'), ('Z4', 'Littoral et Sud-Ouest'), ('Z5', 'Centre, Sud, Est'), ('INTERNATIONAL', 'International')], default='AUCUNE', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Image')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
