# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180307_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=news.models.article_image, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
