# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20180405_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=userProfile.models.user_image, verbose_name='avatar'),
        ),
    ]
