# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-30 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('surface', models.IntegerField(default=0)),
                ('treeNursery', models.BooleanField(default=False)),
                ('treeNumberByHectare', models.IntegerField(default=0)),
                ('semDensity', models.IntegerField(default=0)),
                ('fertilizerProportion', models.IntegerField(default=0)),
                ('phytoThreatment', models.IntegerField(default=0)),
                ('productPrice', models.IntegerField(default=0)),
                ('semDate', models.DateTimeField()),
                ('cropDate', models.DateTimeField()),
                ('cropTotalProduct', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.BooleanField(default=False)),
                ('avdanced', models.BooleanField(default=False)),
                ('professional', models.BooleanField(default=False)),
                ('zone', models.CharField(choices=[('Z1', 'Soudano sahélienne (Nord et Extrême Nord)'), ('Z2', 'Hautes savanes guinéennes (Adamaoua, département du mbam)'), ('Z3', 'Hauts plateaux de l’ouest (Ouest et Nord-Ouest)'), ('Z4', 'Forets humides a pluviométries monomodale (Littoral et Sud-Ouest)'), ('Z5', 'Foret humide a pluviométrie bimodale (Centre, Sud, Est)')], max_length=200)),
                ('product', models.CharField(choices=[('ARACHIDE', 'Arachide'), ('CACAO', 'Cacao'), ('MAIS', 'Maïs'), ('MANIOC', 'Manioc'), ('PLANTAIN', 'Plantain')], max_length=50)),
                ('surface', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Projects Starters',
                'ordering': ['-id'],
            },
        ),
    ]
