# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-02 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstarter',
            name='avdanced',
        ),
        migrations.RemoveField(
            model_name='projectstarter',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='projectstarter',
            name='professional',
        ),
    ]
