# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180402_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstarter',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='projectstarter',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectstarter',
            name='zone',
            field=models.CharField(max_length=200),
        ),
    ]
