# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180402_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstarter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
    ]
