# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180402_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.CharField(default='basic', max_length=50),
        ),
    ]
